### PR TITLE
add optional callback for stopping the consumer

### PR DESCRIPTION
**Pull request by anho**
Hi,

I have a similar need as #15 as I'm running Node on AWS and ECS/Docker notifies a running container with a SIGTERM when it should be stopped. And as I'd like to handle this in a correct way, here is the proposal for it.

### CODE REVIEW

**Comment by robinjmurphy** [comment]
Hi @anho. Thanks for the PR. Are you OK to add this to the README in your branch? Maybe just document the argument here https://github.com/bbc/sqs-consumer#consumerstop and summarise when it is called (i.e. one the current polling request has ended).

**Comment by DaMouse404** [comment]
Just one concern, if I called `stop` and then immediately called `start` then this would continue calling the `handleStop` function on every `_poll`. This also only allows for one callback to exist for the `stop` handler. Maybe this would be better off as a `stopped` event which is fired on the first `_poll` after the `stopped` flag has been set? 

Would this work for you @anho ?

**Comment by anho** [comment]
@robinjmurphy if we can agree on the implementation I'm fine with adding it to the readme :) What do you think about the suggestion of @DaMouse404 ? Personally I don't have a strong opinion about it, but I think it does not fit the way this module is designed in general. Still, its your call and I'm fine with just being able to achieve what I want.

**Comment by robinjmurphy** [comment]
I think Chris's suggestion would be best as it means we can avoid the edge cases around what happens to the callback when the consumer is started/stopped multiple times.

Let's implement a simple `stopped` event which fires when the consumer finishes polling.

**Comment by anho** [comment]
See #41 for the implementation of the event.

**Pull request closed without merging**
