### PR TITLE
Ack partial of a batch of messages

### PR DESCRIPTION
**Pull request by efiShtain**
## Description
When providing a handleMessageBatch function, code currently allows ack all messages or throw an error which will reject all messages.
The fix allows the user to return an array of successful messages which will be deleted from the queue, the rest of the messages will return to the queue

## Motivation and Context
Added for personal use and response to issue 245
https://github.com/bbc/sqs-consumer/issues/245

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by oursodon** [comment]
I'd love to see this PR merged 🙏

**Comment by BotchM** [comment]
This would be really helpful

**Comment by mcflypl** [comment]
I am waiting for merge this pull request :)

**Comment by ellisium** [comment]
Any feedback if it will be merged? And if yes, when will it be?

**Comment by franciscomemoli** [comment]
I need this too. Anyone using this lib needs it, is the only way to process in batch and handle erros.

**Comment by vyrtus15** [comment]
@nspragg  @robinjmurphy UP

**Comment by markussiebert** [comment]
Would be nice to see this getting merged :-)

**Comment by nicholasgriffintn** [comment]
I see there are a fair amount of comments on this, however, it is out of date by a little, would be good to update this and then we can look at it in a future milestone.

**Review by nicholasgriffintn — APPROVED** [review]
Tested this locally and it works as expected.

I have updated this to work with AWS SDK V3 and I've also added a test for if handleMessageBatch returns void, which should delete all of the messages.

**Pull request merged**
