### PR TITLE
Add empty queue event

### PR DESCRIPTION
**Pull request by jacanotrigueros**
Add empty queue event. When all messages have been consumed emit 'emptyQueue' and continues with the poll (you know when you can stop sqs consumer).

Include:
- Updated tests
- Updated documentation

### CODE REVIEW

**Comment by robinjmurphy** [comment]
Hi @jacanotrigueros. Can you walk me through your use case for this event?

The point of this library is that you have a process that's constantly polling for messages. If you just want to process all the messages on the queue and then stop, maybe the AWS SDK is a better option?

**Comment by jacanotrigueros** [comment]
Hi @robinjmurphy,

This event lets you know if the queue is empty. It's optional (default is not emit) and will not stop the poll.

It's good to know if you should create more consumers (the event isn't issued because queue has too many messages). 

You get the number of consumers can be dynamic.

Regards!

**Comment by robinjmurphy** [comment]
Ok. Could you give me an example of what your listener might look like for an `empty` event?

Am I right in thinking you'll use it to work out when to scale your consumers?

**Comment by jacanotrigueros** [comment]
Yes @robinjmurphy,

An example:

`function SQSWorkers(options) {
  ...
  this.configuration.consumer = options.configuration.consumer;
  this.configuration.timeout = options.configuration.timeout;
  
  this.numberWorkers = 1;
  this.consumerWorkers = [];
  this.queueIsEmpty = false;
  ...
}
....

SQSWorkers.prototype._createConsumer = function (index) {
  ...
  var consumer = Consumer.create(this.configuration.consumer);
  consumer.start();
  this.consumerWorkers[index] = consumer;
  ...
};

SQSWorkers.prototype._deleteConsumer = function (index) {
  ...
};

SQSWorkers.prototype.start = function () {
  ....
  var consumer = Consumer.create(this.consumer.configuration);
  this.consumerWorkers[0] = consumer;

  consumer.start();
  
  consumer.on('emptyQueue', function (err) {
    this.queueIsEmpty = true;
  });
  ...

  var that = this;
  setTimeout(function() {
    if (that.numberWorkers != 1) {
      if (!that.queueIsEmpty) {
        that._createConsumer(++that.numberWorkers);
      } else {
        that._deleteConsumer(--that.numberWorkers);
      }
    }
    that.queueIsEmpty = false;
  }, this.configuration.timeout);
  ...
};

....`

Sorry for all errors!

Regards!

**Comment by robinjmurphy** [comment]
Thanks for the example.

I think we should be able to get this in. There are a few things that I think we could change though:

* The event doesn't need to be optional - people are free to ignore it if it's not useful to them. Let's _always_ fire it when the consumer receives an empty response
* Let's change the event name to `empty` as it's simpler
* I don't quite see why we need the `this.queueIsNotEmpty` property - I think we can just send the event in that `else` block - but maybe I've missed something?

**Comment by jacanotrigueros** [comment]
Hi @robinjmurphy, 

Ok, I close this pull request and create a new with the changes.

Regards!

**Pull request closed without merging**
