### PR TITLE
Added 'AttributeNames' option

### PR DESCRIPTION
**Pull request by pablovilas**
Attributte name option changed. Please check: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html
Thanks

### CODE REVIEW

**Comment by hjerling** [comment]
Hi @pablovilas,

`AttributeNames` and `MessageAttributeNames` are two different things. 

- `AttributeNames` is for getting information back with regard to the queue.
- `MessageAttributeNames` is for getting information back with regard to the messages.

See http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html#receiveMessage-property for more detail. In the example you can see how the two properties are used. 

if you would like to add support for `AttributeNames` that would be great and very appreciated!  Please make sure to add some tests and update the [`README.md`](https://github.com/bbc/sqs-consumer/blob/master/README.md) accordingly.

Let us know what you decide to do and close this pull request if you decide against fixing it.

**Comment by pablovilas** [comment]
Sure!. I'll update the pr

**Comment by pablovilas** [comment]
I've updated the pr with your suggestions. Thanks.

**Comment by pablovilas** [comment]
Can you please accept/decline the pr?. Thanks.

**Comment by hjerling** [comment]
Sorry for the delay. 
It all looks good.
:+1:

**Comment by pablovilas** [comment]
Thanks!, can you please update npm?.

**Comment by hjerling** [comment]
Oh, I forgot about npm. Sorry.

**Comment by pablovilas** [comment]
It's ok :). Installed and running!. Thanks.

**Pull request merged**
