### PR TITLE
add support for processing more than 10 messages concurrently

### LINKED ISSUE #96: Process more than 10 messages in parallel
By default messages are processed one at a time – a new message won't be received until the first one has been processed. To process messages in parallel, use the batchSize option detailed below.
Can batchSize runs the different messages simultaneously at the same time and thus fetch remaining messages if any from the AWS SQS and then execute them as well or we have to apply parent and child process for parallel execution of multiple messages from the aws SQS

### PR DESCRIPTION
**Pull request by schmod**
## Description

This change implements an internal work-queue inside of SQS-consumer using [fastq](https://www.npmjs.com/package/fastq).

This change enables SQS-consumer to process more than 10 messages concurrently, and also allows messages to be internally buffered.

## Motivation and Context

This change enables or improves a few use-cases:
* Queue workers can now process more than 10 messages at a time.  
* Queue workers no longer need to wait for an entire batch of messages to be processed before moving on to the next batch.  This can significantly improve performance/efficiency in scenarios where processing-time varies between messages.  

Additionally, by tracking work in a queue, it becomes possible to implement other features later on:
* Graceful shutdowns (`consumer.stop()` can return a promise that resolves when the internal queue drains)
* Exposing more detailed metrics (beyond `isRunning`) about the status of the consumer

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Resolves #96 and #229

### CODE REVIEW

**Comment by schmod** [comment]
Apologies for opening a PR without first creating an issue.  This is functionality that we need for an internal project, and we were going to build it one way or the other.  Feel free to close if this is not something that you'd like to adopt in the library.

**Review by tomwinnington — DISMISSED** [review]

**Comment by nicholasgriffintn** [comment]
These changes look to have been approved (new settings dismissed it), will need a triage and update due to its age though.

**Comment by nicholasgriffintn** [comment]
It looks like the previous suggestion was that this library should be limited to 10 messages at a time: https://github.com/bbc/sqs-consumer/issues/96#issuecomment-340734863

I'm unsure if that's the best way of doing it though, I need to think about the advantages and disadvantages of doing this, in particular, I see we are using an additional library, which does add overhead that we'll need to support and ship, so some further consideration should be made.

**Comment by schmod** [comment]
I'll likely publish a fork if this is indeed a non-goal of `sqs-consumer` – the ability to buffer messages and process more than 10 at a time is unfortunately rather important for many workloads.  

I appreciate the desire to keep this library as lightweight as possible, but I also wasn't able to identify a good pattern for building this functionality on top of sqs-consumer without modifying its internals.  (If there was a way to expose an interface where this was possible, I'd support that.... but I'm not convinced that there is)

**Comment by nicholasgriffintn** [comment]
I think given the age of this PR and the resolutions, it may be best to close this for now and look at this in a future version of sqs-consumer.

I have added an item on the [Roadmap](https://github.com/bbc/sqs-consumer/discussions/328) to look into this. Thanks for the contribution, but I'd like to fully understand our options here first as it's a big change to the library.

**Pull request closed without merging**
