### PR TITLE
fix: removing bind and refactoring consumer

### PR DESCRIPTION
**Pull request by mogu4iy**
Resolves #NUMBER

**Description:**

There is an inheritance issue, that it's not possible to extend Consumer class. It happens because you autoBind all propertyNames from constructor.prototype, so while extending these properties are not accessible anymore in this way.

**Type of change:**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

**Why is this change required?:**

There are cases when we what to extend Consumer class, to pass pre defined options for example.
I have created [minimal reproducible exaple](https://github.com/mogu4iy/sqs-consumer-inheritance-issue).

**Code changes:**

- Add missing type declarations
- Remove autoBind usage to let extend this class
- Update passing in-class methods to intervals using arrow functions to solve context passing issue

---

**Checklist:**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mogu4iy** [comment]
@nicholasgriffintn I hope you can check this as well ;)

**Comment by nicholasgriffintn** [comment]
Hey, thanks for the PR.

I'm not too sure the reasoning behind the bind, and if we need it or not honestly, it's before my time.

I'll have to have a look through this when I have a spare hour or two, bare with :).

**Comment by mogu4iy** [comment]
> Hey, thanks for the PR.
> 
> I'm not too sure the reasoning behind the bind, and if we need it or not honestly, it's before my time.
> 
> I'll have to have a look through this when I have a spare hour or two, bare with :).

It was used to avoid passing class methods to intervals or promise then calls using arrow functions.

**Comment by nicholasgriffintn** [comment]
Yeh it was part of the original commit years ago, so potentially just old Node/JS thoughts. I'll have a proper look through tomorrow.

**Comment by mogu4iy** [comment]
@nicholasgriffintn any updates?

**Comment by mogu4iy** [comment]
I am also interested in estimates, when you are going to release 10.0.0

**Review by nicholasgriffintn — APPROVED** [review]
Sorry for the delay, got stuck with the day job. This will be in `v10.0.0-canary.3` and eventually `v10`.

We don't have a date for version 10 yet, ultimately it will be whenever we feel confident to release it without risk of issues, we've not yet done the testing for that, in the meantime, the canary version can be installed.

**Pull request merged**
