### PR TITLE
AWS IAM Permissions with Policy Example

### PR DESCRIPTION
**Pull request by dmitry-livchak**

### CODE REVIEW

**Comment by cejast** [comment]
It's a helpful note, but we probably don't need the example IAM policy.

**Comment by dmitry-livchak** [comment]
Why not? This is common practice to get developers up to speed with core platform setup.

**Comment by cejast** [comment]
The README should explain how to use the library, not how to set up AWS infrastructure.

We can still keep the note on which actions are required, but going into examples of IAM policies is too much. Information on setting up resources is what the AWS docs are for.

**Comment by dmitry-livchak** [comment]
Fair enough! Removed the sample.

**Comment by cejast** [comment]
Thanks @dmitry-livchak

**Pull request merged**
