### PR TITLE
Stops the consumer when there is a config error

### LINKED ISSUE #23: consumer does not regulate itself and takes 100% cpu when no AWS creds given
I just spent some time finding out the hard way (after restarting a virtual machine in the cloud) that your library does not inspect it's environment, nor does it regulate its own sanity...pffff

please kill the loop if the environment is not sane, as in no aws creds found etc...

### PR DESCRIPTION
**Pull request by diorahman**
Stops the consumer when one of the possibe config errors is received. The possibe config errors are as follows:
  - Missing credentials in config.
  - The request signature we calculated does not match the signature you
    provided.
  - The security token included in the request is invalid.

Possibly could close #23.

### CODE REVIEW

**Comment by robinjmurphy** [comment]
Thanks @diorahman. Have tested it out and it does what we want.

I'm interested in seeing if we can make the error check less reliant on the error message string. Having done a quick test it looks like when the credentials are missing the error includes a `code` property set to `CredentialsError`. When the credentials are wrong or you get a signature mismatch then the `statusCode` property is set to `403`.

Maybe we could extract that error check into a named function (`isAuthenticationError`?) and use a combination of the `code` and `statusCode` properties to implement the check?

One more thing I wanted to get your feedback on: another way to solve the CPU issue would be to not stop the consumer when an error occurs but instead just wait temporarily (say, 10 seconds) before polling again. This means that if you've just missed out some IAM config you can fix it in the console and the consumer will just start working when it retries.

**Comment by diorahman** [comment]
@robinjmurphy will definitely take an attempt per your suggestions. Do you think I need to create another PR or put a subsequent commits?

**Comment by robinjmurphy** [comment]
Keep going with the commits I think.

**Comment by diorahman** [comment]
@robinjmurphy I'm not sure about the test, do you have suggestions on checking the 10 seconds pause?

**Comment by robinjmurphy** [comment]
I'll try and take a look today or tomorrow for you @diorahman.

**Comment by robinjmurphy** [comment]
I think this is OK @diorahman. I think we can make the error timeout configurable and set it to a low value for the tests. Will merge later and make that change once it's in. Thanks.

**Pull request merged**
